[project]
name = "noisepalace"
version = "0.1.0"
description = "Soon to be a well documented library of many noise functions."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
]

[dependency-groups]
dev = [
    "basedpyright>=1.34.0",
    "ruff>=0.14.6",
]
